name: Send Email Notification

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  pull_request_target:
    branches:
      - '**'

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install nodemailer

      - name: Send email notification
        run: node sendEmail.js
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
